pool:
  vmImage: ubuntu-latest
steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'custom'
      custom: 'tool'
      arguments: 'update --global Cake.Tool --version 0.37.0'
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'Sonar'
      organization: 'project-initium'
      scannerMode: MSBuild
      projectKey: 'initium-empty'
      extraProperties: |
        sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
  - task: DotNetCoreCLI@2
    inputs:
      command: 'custom'
      custom: 'cake'
      workingDirectory: './Build'
  - task: PublishTestResults@2
    displayName: Publish Test Results coverage/xunit-report.xml
    inputs:
      testResultsFormat: XUnit
      testResultsFiles: '**/xunit-report.xml'
    continueOnError: true
  - task: PublishCodeCoverageResults@1
    displayName: Publish code coverage from coverage/cobertura-coverage.xml
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: build/build-artifacts/cover/coverage.cobertura.xml
    continueOnError: true
  - task: SonarCloudAnalyze@1
  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'